### ISSUE TITLE
Keeps vibrating when screen is off

### ISSUE THREAD

**Issue by mlagerberg** [pflammertsma/levelizer#16]
Open the camera, take a picture, turn off the screen without closing the camera app: Levelizer keeps giving haptic feedback.

Tested on Nexus 6P, Nougat preview.

**Comment by pflammertsma** [comment]
This suggests to me that _both_ no accessibility event _and_ no screen off broadcast is fired when the screen is switched off. Perhaps something has changed on Nougat?

**Comment by mlagerberg** [comment]
Well whaddayaknow, got the latest Nougat preview just an hour ago and now it's fixed.
